### ISSUE TITLE
aanpassingen ikv gemeentefusies

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/oe_dojo#175]
- Bij zoekopdrachten naar actoren param ?geldige_actor=true toevoegen
- Extra parameter status=inGebruik toevoegen bij ophalen gemeenten, straten en adressen
- Andere dojo libs updaten die aangepast zijn voor gemeentefusies

**Comment by AxelVerstappen** [comment]
Geen aanpassingen nodig
