### ISSUE TITLE
Openbaar domein bij LocatiePercelen

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/oe_dojo#26]

**Comment by taeymma** [comment]
Hoe zit het nu precies met Openbaar Domein? Heb al verschillende dingen gehoord.. 

Checkbox met vrij tekstveld? of met niscode select? of weglaten?

**Comment by kmillet** [comment]
Dat zal @jolijnleen beter weten. De info die ik heb staat op https://github.com/OnroerendErfgoed/notas/issues/418

**Comment by jolijnleen** [comment]
Dat is ook alle info die ik heb..
We houden de knop bij proces toevalsvondsten, 
Bij (archeologie)nota's, meldingen vooronderzoek, archeologierapporten en eindverslagen mag hij verborgen worden.

**Comment by kmillet** [comment]
Lijkt me voorlopig enkel van belang voor de toevalsvondsten. Ik sluit hierbij dit ticket  af.
