### ISSUE TITLE
Update AGIV wfs url

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/oe_dojo#44]
http://geoservices.informatievlaanderen.be/overdrachtdiensten/GRB/wfs

en laagnaam van administratieve percelen is veranderd naar: GRB:ADP

**Comment by cedrikv** [comment]
fixed in dev_0.2

**Comment by cedrikv** [comment]
ogcproxy nog eruit halen

**Comment by cedrikv** [comment]
fixed in dev_0.2
